-- SeatSync core schema.
-- Database constraints are the second safety layer behind application-level locking:
-- even if a code path skipped the seat lock, PostgreSQL rejects a double allocation.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(150)  NOT NULL,
    description    VARCHAR(2000) NOT NULL,
    category       VARCHAR(30)   NOT NULL,
    venue          VARCHAR(150)  NOT NULL,
    city           VARCHAR(80)   NOT NULL,
    event_date     DATE          NOT NULL,
    start_time     TIME          NOT NULL,
    image_url      VARCHAR(500),
    status         VARCHAR(20)   NOT NULL,
    row_count      INT           NOT NULL,
    seats_per_row  INT           NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_events_status CHECK (status IN ('ON_SALE', 'PAUSED')),
    CONSTRAINT ck_events_category CHECK (category IN ('CONCERT', 'COMEDY', 'THEATRE', 'SPORTS', 'CONFERENCE', 'WORKSHOP')),
    CONSTRAINT ck_events_layout CHECK (row_count BETWEEN 1 AND 26 AND seats_per_row BETWEEN 1 AND 40)
);

-- Event discovery lists upcoming events ordered by date/time.
CREATE INDEX ix_events_date_time ON events (event_date, start_time);

CREATE TABLE seats (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         BIGINT        NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    seat_number      VARCHAR(10)   NOT NULL,
    row_label        VARCHAR(2)    NOT NULL,
    seat_index       INT           NOT NULL,
    section          VARCHAR(20)   NOT NULL,
    price            NUMERIC(10, 2) NOT NULL,
    status           VARCHAR(20)   NOT NULL,
    held_by_user_id  BIGINT        REFERENCES users (id),
    hold_expires_at  TIMESTAMPTZ,
    version          BIGINT        NOT NULL DEFAULT 0,
    -- A seat can never exist twice for the same event. Also serves every "seats of event X" lookup.
    CONSTRAINT uk_seats_event_seat_number UNIQUE (event_id, seat_number),
    CONSTRAINT ck_seats_status CHECK (status IN ('AVAILABLE', 'RESERVED', 'BOOKED')),
    CONSTRAINT ck_seats_section CHECK (section IN ('VIP', 'PREMIUM', 'STANDARD')),
    CONSTRAINT ck_seats_price CHECK (price > 0),
    CONSTRAINT ck_seats_index CHECK (seat_index > 0),
    -- A RESERVED seat always has a holder and an expiry; other states never do.
    CONSTRAINT ck_seats_hold_consistency CHECK (
        (status = 'RESERVED' AND held_by_user_id IS NOT NULL AND hold_expires_at IS NOT NULL)
        OR (status <> 'RESERVED' AND held_by_user_id IS NULL AND hold_expires_at IS NULL)
    )
);

-- Availability counts per event (event cards, admin monitoring) become index-only scans.
CREATE INDEX ix_seats_event_status ON seats (event_id, status);

-- The hold sweeper only ever looks at reserved seats; a partial index keeps it tiny.
CREATE INDEX ix_seats_hold_expiry ON seats (hold_expires_at) WHERE status = 'RESERVED';

CREATE TABLE bookings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference     VARCHAR(12)    NOT NULL,
    user_id       BIGINT         NOT NULL REFERENCES users (id),
    event_id      BIGINT         NOT NULL REFERENCES events (id),
    total_amount  NUMERIC(12, 2) NOT NULL,
    status        VARCHAR(20)    NOT NULL,
    booking_time  TIMESTAMPTZ    NOT NULL,
    cancelled_at  TIMESTAMPTZ,
    version       BIGINT         NOT NULL DEFAULT 0,
    CONSTRAINT uk_bookings_reference UNIQUE (reference),
    CONSTRAINT ck_bookings_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT ck_bookings_amount CHECK (total_amount >= 0),
    CONSTRAINT ck_bookings_cancellation CHECK ((status = 'CANCELLED') = (cancelled_at IS NOT NULL))
);

-- "My bookings": filter by user, newest first.
CREATE INDEX ix_bookings_user_time ON bookings (user_id, booking_time DESC);
-- Admin filtering by event/status and the "event has bookings" delete guard.
CREATE INDEX ix_bookings_event_status ON bookings (event_id, status);
-- Admin booking feed and the dashboard's daily chart scan by time.
CREATE INDEX ix_bookings_time ON bookings (booking_time DESC);

CREATE TABLE booking_seats (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  BIGINT         NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
    seat_id     BIGINT         NOT NULL REFERENCES seats (id),
    price       NUMERIC(10, 2) NOT NULL,
    active      BOOLEAN        NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_booking_seats_booking_seat UNIQUE (booking_id, seat_id),
    CONSTRAINT ck_booking_seats_price CHECK (price >= 0)
);

-- The hard guarantee: a seat can belong to at most one active (non-cancelled) booking.
-- Cancelling a booking flips `active` to false, freeing the seat for a new booking.
CREATE UNIQUE INDEX ux_booking_seats_active_seat ON booking_seats (seat_id) WHERE active;
